Repository Sadna-Team/TradeCenter, pull requests merged in 2024-07, with the labels that each got.

#370 now a manager will only have access to store management based on thei…
  backend/app.log
  backend/business/market.py
  backend/business/roles/roles.py
  backend/services/user_services/routes.py
  frontend/app/stores/[storeId]/page.js
Labels: enhancement

#374 369 system manager main window
  backend/business/DTOs.py
  backend/business/market.py
  backend/business/store/new_store.py
  backend/services/store_services/controllers.py
  backend/services/store_services/routes.py
  frontend/app/layout.js
  frontend/app/search_products/search_by_category/page.js
  frontend/app/system-manager/page.js
  frontend/components/CategorySearchBar.jsx
  frontend/components/Sidebar.jsx
Labels: enhancement

#377 added support for getting unemployed employees in the store
  backend/app.log
  backend/business/market.py
  backend/business/roles/roles.py
  backend/business/user/user.py
  backend/services/user_services/controllers.py
  backend/services/user_services/routes.py
Labels: enhancement

#378 added the employee nomination page
  frontend/app/manage_employee/[storeid]/page.js
  frontend/app/nominate-employees/[storeid]/page.js
Labels: enhancement

#381 380 enable category modifications for store manager
  backend/app.log
  backend/business/market.py
  backend/business/store/new_store.py
  backend/services/store_services/controllers.py
  backend/services/store_services/routes.py
  frontend/app/stores/[storeId]/edit-product-categories/[productId]/page.js
  frontend/app/stores/[storeId]/page.js
  frontend/components/ManagerProduct.jsx
Labels: enhancement

#383 can unassign categories!
  backend/services/store_services/controllers.py
  backend/services/store_services/routes.py
  frontend/app/system-manager/page.js
Labels: enhancement

#386 can view stores & purchase history in stores
  backend/app.log
  backend/business/DTOs.py
  backend/business/market.py
  backend/business/purchase/purchase.py
  backend/business/store/new_store.py
  backend/services/ecommerce_services/routes.py
  backend/services/store_services/controllers.py
  backend/services/store_services/routes.py
  frontend/app/system-manager/page.js
  frontend/app/system-manager/store-management/page.js
  frontend/app/system-manager/store-management/store-purchase-history/[storeId]/page.js
Labels: enhancement

#389 minor fix
  frontend/app/system-manager/page.js
  frontend/app/system-manager/store-management/page.js
Labels: bug, frontend

#399 works!
  backend/business/ThirdPartyHandlers/third_party_handlers.py
  backend/business/market.py
  backend/services/third_party_services/controllers.py
  backend/services/third_party_services/routes.py
  frontend/app/checkout/page.js
  frontend/app/stores/[storeId]/edit-product-categories/[productId]/page.js
  frontend/app/system-manager/page.js
  frontend/app/system-manager/third-party-management/page.js
Labels: enhancement

#401 small bug made constraint type forms not load, fixed now
  frontend/app/discounts/page.js
Labels: bug

#403 402 fixing discount and policy front
  backend/app.log
  backend/business/market.py
  backend/business/store/PurchasePolicy.py
  backend/business/store/discount.py
  frontend/app/date_discount/page.js
  frontend/app/discounts/page.js
  frontend/app/manage_policy/[id]/page.js
Labels: bug

#405 404 adding maxamount
  backend/business/store/constraints.py
  backend/business/store/new_store.py
  frontend/app/discounts/page.js
  frontend/app/manage_policy/[id]/page.js
  tests/acceptance_test_checkout.py
  tests/store_owner_more_actions_acceptance_test.py
  tests/unit_tests/test_constraint.py
  tests/unit_tests/test_discount.py
  tests/unit_tests/test_new_store.py
  tests/unit_tests/test_purchase_policy.py
Labels: enhancement

#406 267 adding the implementation of bid purchase adding all relevant tests
  backend/business/DTOs.py
  backend/business/market.py
  backend/business/purchase/purchase.py
  backend/error_types.py
  backend/services/ecommerce_services/controllers.py
  backend/services/ecommerce_services/routes.py
  backend/services/store_services/routes.py
  tests/acceptance_tests_system_manager.py
  tests/integration_tests.py
  tests/store_owner_more_actions_acceptance_test.py
  tests/unit_tests/test_purchase.py
Labels: bug, documentation, enhancement

#416 408 api connection to third party services
  backend/__init__.py
  backend/business/ThirdPartyHandlers/third_party_handlers.py
  backend/business/market.py
  backend/business/store/new_store.py
  backend/error_types.py
  backend/requirements.txt
  backend/services/ecommerce_services/routes.py
  backend/services/store_services/routes.py
  frontend/app/checkout/page.js
  frontend/components/ExternalPaymentDetails.jsx
  frontend/components/ExternalSupplyDetails.jsx
  tests/acceptance_test_checkout.py
  tests/concurrency_test.py
  tests/integration_tests.py
  tests/store_owner_actions_acceptance_test.py
  tests/unit_tests/test_third_party_handlers.py
Labels: documentation, enhancement, tests, frontend

#429 DONE
  backend/app.log
  backend/business/DTOs.py
  backend/business/authentication/authentication.py
  backend/business/market.py
  backend/services/__init__.py
  backend/services/store_services/controllers.py
  backend/services/store_services/routes.py
  frontend/app/cart/page.js
Labels: documentation, enhancement, database

#433 added error checking in purchase policy
  backend/business/store/PurchasePolicy.py
  backend/error_types.py
Labels: bug, documentation, enhancement

#436 added error checking that was missing in new store
  backend/business/store/new_store.py
  backend/error_types.py
Labels: bug, documentation, enhancement

#440 421 error checking in backend for constraints
  backend/business/store/constraints.py
  backend/business/store/new_store.py
  backend/error_types.py
Labels: bug, documentation, enhancement

#442 fixing tests
  backend/business/authentication/authentication.py
  tests/unit_tests/test_authentication.py
Labels: bug

#443 415 changing the implementation of discounts to be store specific and not system generic making it so that store ownersmanagers manage the discounts of store
  backend/business/market.py
  backend/business/store/discount.py
  backend/business/store/new_store.py
  backend/services/store_services/controllers.py
  backend/services/store_services/routes.py
  frontend/app/discounts/[id]/page.js
  frontend/app/stores/[storeId]/page.js
  frontend/components/ManagerDiscount.jsx
  frontend/components/Sidebar.jsx
  tests/acceptance_tests_system_manager.py
  tests/integration_tests.py
  tests/store_owner_more_actions_acceptance_test.py
  tests/unit_tests/test_discount.py
  tests/unit_tests/test_new_store.py
  tests/unit_tests/test_purchase_policy.py
  tests/unit_tests/test_store.py
Labels: bug, documentation, enhancement, frontend

#445 418 bid checkout implement
  backend/business/market.py
  backend/business/purchase/purchase.py
  backend/error_types.py
Labels: documentation, enhancement

#451 448 add db support in store
  backend/__init__.py
  backend/app.py
  backend/app_factory.py
  backend/business/market.py
  backend/business/purchase/purchase.py
  backend/business/store/new_store.py
  backend/services/__init__.py
  backend/services/store_services/controllers.py
  tests/unit_tests/test_new_store.py
Labels: bug, enhancement, database

#453 add timeout to external API
  backend/business/ThirdPartyHandlers/third_party_handlers.py
Labels: bug, enhancement

#455 454 connect active third party handlers to db
  backend/business/ThirdPartyHandlers/third_party_handlers.py
  backend/business/market.py
Labels: enhancement, database

#460 420 bid frontend
  backend/app.log
  backend/business/market.py
  backend/business/purchase/purchase.py
  backend/services/ecommerce_services/controllers.py
  backend/services/ecommerce_services/routes.py
  frontend/app/bid-status/page.js
  frontend/app/bids-of-system/page.js
  frontend/app/cart/page.js
  frontend/app/checkout_bid/[bidId]/page.js
  frontend/app/discounts/[id]/page.js
  frontend/app/e-store/[storeid]/[productid]/page.js
  frontend/app/globals.css
  frontend/app/manage_bids/[storeId]/page.js
  frontend/app/stores/[storeId]/page.js
  frontend/app/user_manage_bids/page.js
  frontend/components/Sidebar.jsx
Labels: bug, documentation, enhancement, frontend

#463 implemented error checking in user
  backend/business/user/user.py
  backend/error_types.py
Labels: bug, documentation

#464 very minor error checking that was missing in purchases
  backend/business/purchase/purchase.py
Labels: bug

#469 446 connect notification to db
  backend/app.py
  backend/business/authentication/authentication.py
  backend/business/notifier/notifier.py
  backend/services/__init__.py
  tests/unit_tests/test_notifier.py
Labels: tests, database

#471 Fixing acceptance tests
  app.log
  backend/app.log
  backend/app.py
  backend/app_factory.py
  backend/business/authentication/authentication.py
  backend/business/market.py
  backend/business/purchase/purchase.py
  backend/business/roles/roles.py
  backend/business/user/user.py
  backend/database.py
  backend/services/__init__.py
  backend/services/store_services/controllers.py
  tests/acceptance_test_checkout.py
  tests/acceptance_tests_system_manager.py
  tests/acceptance_tests_user.py
  tests/concurrency_test.py
  tests/integration_tests.py
  tests/notification_test.py
  tests/store_owner_more_actions_acceptance_test.py
  tests/unit_tests/test_authentication.py
  tests/unit_tests/test_purchase.py
  tests/unit_tests/test_roles.py
Labels: bug, enhancement, tests, database

#472 Fixing acceptance tests
  backend/app_factory.py
Labels: bug, tests

#473 backend is running what do you want from me
  .idea/workspace.xml
  backend/__init__.py
  backend/app.log
  backend/business/authentication/authentication.py
  backend/business/store/new_store.py
  backend/business/user/user.py
  backend/services/__init__.py
  backend/services/user_services/controllers.py
  tests/acceptance_tests_user.py
Labels: bug, enhancement, frontend, database
