Repository Sadna-Team/TradeCenter, pull requests merged in 2024-06, with the labels that each got.

#123 122 third party handlers adding delivery date estimation support and refactoring names
  backend/business/ThirdPartyHandlers/third_party_handlers.py
  backend/business/market.py
  tests/unit_tests/test_third_party_handlers.py
Labels: bug, documentation, enhancement

#132 done
  backend/business/roles/roles.py
Labels: enhancement

#139 👍
  backend/business/user/user.py
Labels: enhancement

#142 👍
  backend/business/notifier/notifier.py
Labels: enhancement

#141 👍
  backend/business/user/user.py
Labels: enhancement

#146 135 refactoring store
  backend/business/DTOs.py
  backend/business/market.py
  backend/business/store/__init__.py
  backend/business/store/new_store.py
  backend/business/store/store.py
  backend/business/store/strategies.py
  backend/tests/test_store.py
  tests/unit_tests/test_new_store.py
  tests/unit_tests/test_purchase.py
  tests/unit_tests/test_store.py
Labels: documentation

#155 147 adding support of purchase policy
  backend/business/DTOs.py
  backend/business/market.py
  backend/business/store/new_store.py
  backend/business/store/strategies.py
  backend/business/user/user.py
  backend/requirements.txt
  tests/unit_tests/test_new_store.py
Labels: documentation, enhancement

#170 162 acceptance tests ilay
  backend/services/ecommerce_services/routes.py
  backend/services/store_services/routes.py
  backend/services/user_services/routes.py
  tests/acceptance_test_store_owner_actions.py
  tests/acceptance_tests_system_manager.py
Labels: tests

#173 checking errors
  tests/acceptance_test_store_owner_actions.py
Labels: tests

#174 done
  backend/business/market.py
  backend/services/store_services/controllers.py
  backend/services/store_services/routes.py
Labels: bug

#175 there is no STORE
  backend/__init__.py
  tests/acceptance_test_store_owner_actions.py
Labels: bug

#178 working
  backend/__init__.py
  backend/services/store_services/routes.py
Labels: bug

#176 167 make logs visible
  app.log
  backend/business/ThirdPartyHandlers/test.py
  backend/business/ThirdPartyHandlers/third_party_handlers.py
  backend/business/market.py
  backend/business/roles/roles.py
  backend/business/store/new_store.py
  backend/business/user/user.py
Labels: enhancement

#180 163 acceptance tests gal
  backend/__init__.py
  backend/business/DTOs.py
  backend/business/authentication/authentication.py
  backend/business/market.py
  backend/business/user/user.py
  backend/services/store_services/routes.py
  backend/services/user_services/controllers.py
  backend/services/user_services/routes.py
  tests/acceptance_tests_roles.py
  tests/acceptance_tests_user.py
Labels: tests

#182 working
  backend/business/ThirdPartyHandlers/third_party_handlers.py
Labels: enhancement

#187 179 fixing store acceptance tests
  backend/business/market.py
  backend/business/user/user.py
  backend/services/store_services/routes.py
  backend/services/user_services/routes.py
  tests/acceptance_test_store_owner_actions.py
Labels: bug, tests

#191 DONE
  pytest.ini
Labels: enhancement, tests

#192 WTH IS GOING ON
  backend/business/market.py
  backend/business/roles/roles.py
  backend/services/store_services/controllers.py
  backend/services/store_services/routes.py
  tests/acceptance_test_store_owner_actions.py
Labels: bug, tests

#194 156 adding locks to allow sync
  backend/business/purchase/purchase.py
  backend/business/store/new_store.py
  tests/unit_tests/test_new_store.py
Labels: documentation, enhancement

#196 fixed store owner actions tests, besides those that have commented ro…
  backend/business/DTOs.py
  backend/business/market.py
  backend/business/roles/roles.py
  backend/business/user/user.py
  backend/services/store_services/controllers.py
  backend/services/store_services/routes.py
  backend/services/user_services/controllers.py
  tests/store_owner_actions_acceptance_test.py
Labels: bug, tests

#197 done
  backend/business/market.py
  backend/business/user/user.py
Labels: enhancement

#199 198 the tests literally just worked why do they not work now
  backend/business/roles/roles.py
  backend/business/store/new_store.py
  tests/store_owner_actions_acceptance_test.py
Labels: bug, tests

#206 148 adding support of discount policy
  backend/business/DTOs.py
  backend/business/address.py
  backend/business/market.py
  backend/business/store/DiscountStrategy.py
  backend/business/store/PurchasePolicyStrategy.py
  backend/business/store/constraints.py
  backend/business/store/discount.py
  backend/business/store/new_store.py
  backend/business/store/store.py
  backend/business/store/strategies.py
  backend/services/ecommerce_services/controllers.py
  backend/services/store_services/controllers.py
  tests/integration_tests.py
  tests/unit_tests/test_constraint.py
  tests/unit_tests/test_discount.py
  tests/unit_tests/test_store.py
Labels: bug, documentation, enhancement

#202 195 finalizing user acceptance tests
  backend/business/DTOs.py
  backend/services/third_party_services/controllers.py
  backend/services/user_services/controllers.py
  tests/acceptance_tests_system_manager.py
  tests/acceptance_tests_user.py
Labels: tests

#207 finished
  backend/business/store/new_store.py
Labels: enhancement

#210 finished
  backend/business/market.py
Labels: bug

#217 i think i done
  backend/business/market.py
  backend/business/user/user.py
  backend/services/store_services/routes.py
  backend/services/user_services/controllers.py
  backend/tests/test_user.py
  tests/acceptance_tests_user.py
  tests/unit_tests/test_authentication.py
  tests/unit_tests/test_new_store.py
  tests/unit_tests/test_user.py
Labels: tests

#212 done
  backend/business/roles/roles.py
  backend/business/store/new_store.py
  tests/acceptance_tests_user.py
  tests/store_owner_actions_acceptance_test.py
  tests/unit_tests/test_authentication.py
  tests/unit_tests/test_new_store.py
  tests/unit_tests/test_third_party_handlers.py
  tests/unit_tests/test_user.py
Labels: bug, tests

#220 added acceptance tests
  tests/store_owner_actions_acceptance_test.py
Labels: tests

#213 209 small fixes in discount implementation
  backend/business/market.py
  backend/business/store/new_store.py
Labels: bug, documentation

#222 214 unit tests new store and discount checkout fixes
  backend/business/DTOs.py
  backend/business/market.py
  backend/business/store/constraints.py
  backend/business/store/discount.py
  backend/business/store/new_store.py
  backend/services/ecommerce_services/controllers.py
  tests/integration_tests.py
  tests/unit_tests/test_constraint.py
  tests/unit_tests/test_discount.py
  tests/unit_tests/test_new_store.py
Labels: bug, documentation, enhancement

#225 huh?
  backend/business/store/new_store.py
Labels: bug, tests

#229 221 testing checkout
  backend/business/DTOs.py
  backend/business/market.py
  backend/business/user/user.py
  backend/services/store_services/controllers.py
  backend/services/store_services/routes.py
  tests/acceptance_test_checkout.py
  tests/store_owner_actions_acceptance_test.py
  tests/unit_tests/test_user.py
Labels: bug, tests

#230 added the test
  tests/concurrency_test.py
Labels: tests

#231 fixed integration
  backend/business/market.py
  backend/business/store/discount.py
  backend/business/store/new_store.py
  tests/integration_tests.py
Labels: bug, documentation

#233 wrote the tests. checkout needs to work before we test it
  tests/concurrency_test.py
Labels: tests

#234 fixed minor error with register_credentials
  tests/concurrency_test.py
Labels: bug, tests

#235 checkout tests done
  tests/acceptance_test_checkout.py
Labels: bug, tests

#237 236 fixing checkout and concurrency tests
  backend/business/market.py
  backend/business/store/new_store.py
  tests/acceptance_test_checkout.py
Labels: bug, tests

#238 tests now run
  tests/concurrency_test.py
Labels: bug, tests

#240 3rd test does not run, both owners succeed for some reason
  tests/concurrency_test.py
Labels: tests

#241 concurrent tests implemented and working
  tests/acceptance_test_checkout.py
  tests/acceptance_tests_roles.py
  tests/concurrency_test.py
Labels: bug, tests

#244 done all except 2.4.13
  backend/business/market.py
  backend/business/store/new_store.py
  backend/services/store_services/controllers.py
  backend/services/store_services/routes.py
  tests/store_owner_actions_acceptance_test.py
Labels: bug, tests

#248 245 writing tests for use case 2221
  backend/business/market.py
  backend/business/purchase/purchase.py
  backend/services/ecommerce_services/controllers.py
  backend/services/ecommerce_services/routes.py
  tests/acceptance_tests_user.py
Labels: bug, tests

#249 157 integration and acceptance
  backend/business/market.py
  backend/business/store/discount.py
  backend/business/store/new_store.py
  backend/services/ecommerce_services/controllers.py
  backend/services/ecommerce_services/routes.py
  backend/services/store_services/routes.py
  tests/acceptance_tests_system_manager.py
  tests/acceptance_tests_user.py
  tests/integration_tests.py
  tests/store_owner_actions_acceptance_test.py
  tests/unit_tests/test_new_store.py
Labels: bug, documentation, enhancement

#251 Added
  tests/integration_tests.py
Labels: tests

#254 fixed locks in store component
  backend/business/store/new_store.py
  tests/concurrency_test.py
  tests/unit_tests/test_new_store.py
Labels: enhancement

#256 255 fixing show purchases of user to receive user
  backend/business/market.py
  backend/services/ecommerce_services/controllers.py
  backend/services/ecommerce_services/routes.py
  tests/acceptance_tests_system_manager.py
  tests/acceptance_tests_user.py
Labels: bug, enhancement

#265 264 fixing to use magic numbers on discount tests as well as changing the creation of constraints
  backend/business/market.py
  backend/business/store/discount.py
  backend/business/store/new_store.py
  backend/services/store_services/controllers.py
  backend/services/store_services/routes.py
  tests/acceptance_tests_system_manager.py
  tests/integration_tests.py
  tests/unit_tests/test_discount.py
  tests/unit_tests/test_new_store.py
Labels: bug, documentation, enhancement

#258 253 adding support for real time notifications
  backend/__init__.py
  backend/app.py
  backend/business/DTOs.py
  backend/business/authentication/authentication.py
  backend/business/market.py
  backend/business/notifier/notifier.py
  backend/business/roles/roles.py
  backend/requirements.txt
  backend/services/store_services/routes.py
  backend/services/user_services/controllers.py
  backend/socketio.py
  tests/acceptance_test_checkout.py
  tests/notification_test.py
  tests/store_owner_actions_acceptance_test.py
  tests/unit_tests/test_notifier.py
Labels: enhancement

#273 made each concurrent test run 1000 times. note that none of them pass…
  tests/concurrency_test.py
Labels: bug, tests

#281 268 fixing purchase policy
  backend/business/DTOs.py
  backend/business/market.py
  backend/business/store/PurchasePolicy.py
  backend/business/store/PurchasePolicyStrategy.py
  backend/business/store/constraints.py
  backend/business/store/discount.py
  backend/business/store/new_store.py
  backend/business/store/store.py
  backend/requirements.txt
  backend/services/store_services/controllers.py
  backend/services/store_services/routes.py
Labels: bug, documentation, enhancement

#283 282 adding tests to new constraints purchasepolicy and discount
  backend/business/market.py
  backend/business/store/PurchasePolicy.py
  backend/business/store/constraints.py
  backend/business/store/discount.py
  backend/business/store/new_store.py
  backend/services/store_services/routes.py
  tests/acceptance_tests_system_manager.py
  tests/integration_tests.py
  tests/store_owner_actions_acceptance_test.py
  tests/store_owner_more_actions_acceptance_test.py
  tests/unit_tests/test_constraint.py
  tests/unit_tests/test_discount.py
  tests/unit_tests/test_new_store.py
  tests/unit_tests/test_purchase_policy.py
Labels: bug, documentation, enhancement

#284 266 error type checking
  backend/business/ThirdPartyHandlers/third_party_handlers.py
  backend/business/authentication/authentication.py
  backend/business/market.py
  backend/business/notifier/notifier.py
  backend/business/purchase/purchase.py
  backend/business/roles/roles.py
  backend/business/store/constraints.py
  backend/business/store/discount.py
  backend/business/store/new_store.py
  backend/business/user/user.py
  backend/error_types.py
  backend/services/ecommerce_services/routes.py
  backend/services/store_services/routes.py
  tests/acceptance_test.py
  tests/acceptance_test_checkout.py
  tests/concurrency_test.py
  tests/integration_tests.py
  tests/unit_tests/test_authentication.py
  tests/unit_tests/test_new_store.py
  tests/unit_tests/test_notifier.py
  tests/unit_tests/test_purchase.py
  tests/unit_tests/test_purchase_policy.py
  tests/unit_tests/test_roles.py
  tests/unit_tests/test_third_party_handlers.py
  tests/unit_tests/test_user.py
Labels: bug, documentation, enhancement

#290 added routes for user suspension
  backend/services/user_services/controllers.py
  backend/services/user_services/routes.py
Labels: enhancement

#293 286 adding search bar pages to frontend
  frontend/README.md
  frontend/app/search_products/page.js
  frontend/app/search_products/search_by_category/page.js
  frontend/app/search_products/search_by_name/page.js
  frontend/app/search_products/search_by_tags/page.js
  frontend/components/CategorySearchBar.jsx
  frontend/components/NameSearchBar.jsx
  frontend/components/Navbar.jsx
  frontend/components/TagSearchBar.jsx
  frontend/package-lock.json
  frontend/package.json
Labels: enhancement

#294 error pop up is working
  .gitignore
  frontend/app/page.js
  frontend/components/ErrorPopup.jsx
Labels: enhancement

#300 299 default setup code
  .gitignore
  backend/__init__.py
  backend/app.log
  backend/business/market.py
  frontend/package-lock.json
  frontend/package.json
  tests/acceptance_test_checkout.py
  tests/acceptance_tests_roles.py
  tests/acceptance_tests_system_manager.py
  tests/acceptance_tests_user.py
  tests/concurrency_test.py
  tests/notification_test.py
  tests/store_owner_actions_acceptance_test.py
  tests/store_owner_more_actions_acceptance_test.py
Labels: tests

#305 now we have Popup, which has the option to disable the close button t…
  frontend/app/page.js
  frontend/components/Popup.jsx
Labels: enhancement

#315 login logic
  backend/app.log
  frontend/app/auth/login/page.js
  frontend/app/auth/register/page.js
  frontend/app/page.js
  frontend/app/socket.js
  frontend/components/ClientNavBar.jsx
  frontend/components/GuestNavBar.jsx
  frontend/components/Navbar.jsx
Labels: enhancement

#318 Finished checkout
  backend/app.log
  frontend/app/bid/page.js
  frontend/app/cart/page.js
  frontend/app/checkout/page.js
  frontend/components/BogoDetails.jsx
Labels: enhancement

#325 Frontend logout
  backend/app.log
  backend/app.py
  frontend/app/AuthContext.js
  frontend/app/auth/login/page.js
  frontend/app/socket.js
  frontend/components/ClientNavBar.jsx
  frontend/components/GuestNavBar.jsx
  frontend/package-lock.json
  tests/acceptance_tests_user.py
Labels: enhancement

#326 minor fix
  frontend/components/Button.jsx
Labels: bug

#329 added axios support. login-logout-tokens work!
  frontend/app/auth/login/page.js
  frontend/app/page.js
  frontend/lib/api.js
Labels: bug

#328 321 add employee management page
  backend/app.log
  frontend/app/manage_discount/[id]/page.js
  frontend/app/manage_discount/page.js
  frontend/app/manage_employee/[id]/page.js
  frontend/app/manage_employee/page.js
  frontend/app/manage_policy/[id]/page.js
  frontend/app/manage_policy/page.js
  frontend/app/stores/[id]/page.js
  frontend/components/User.jsx
  frontend/package-lock.json
Labels: help wanted

#334 Notifications
  backend/__init__.py
  backend/business/market.py
  backend/business/notifier/notifier.py
  backend/services/ecommerce_services/controllers.py
  backend/services/ecommerce_services/routes.py
  frontend/app/auth/login/page.js
  frontend/app/layout.js
  frontend/app/page.js
  frontend/app/socket.js
  frontend/app/socketContext.js
  frontend/components/ClientNavBar.jsx
  frontend/components/Navbar.jsx
  frontend/components/NotificationPopup.jsx
  tests/acceptance_tests_roles.py
Labels: enhancement

#339 done
  frontend/app/stores/[storeId]/edit-product/[productId]/page.js
  frontend/app/stores/[storeId]/page.js
Labels: bug, enhancement

#342 340 connecting searches to backend
  backend/app.log
  backend/business/market.py
  backend/business/store/new_store.py
  backend/services/ecommerce_services/routes.py
  backend/services/store_services/controllers.py
  backend/services/store_services/routes.py
  frontend/app/search_products/search_by_category/page.js
  frontend/app/search_products/search_by_name/page.js
  frontend/app/search_products/search_by_tags/page.js
  frontend/components/CategorySearchBar.jsx
  frontend/components/NameSearchBar.jsx
  frontend/components/TagSearchBar.jsx
Labels: bug, enhancement

#343 332 manage discounts functions for frontend
  backend/business/market.py
  backend/business/store/discount.py
  backend/business/store/new_store.py
  backend/services/store_services/controllers.py
  backend/services/store_services/routes.py
  frontend/app/manage_discount/page.js
  frontend/app/stores/[storeId]/page.js
  frontend/components/ManagerDiscount.jsx
Labels: documentation, enhancement

#348 i should have kept track of my changes XO
  backend/business/market.py
  backend/business/roles/roles.py
  backend/services/store_services/controllers.py
  backend/services/store_services/routes.py
  backend/services/user_services/routes.py
  frontend/app/auth/register/page.js
  frontend/app/layout.js
  frontend/app/my-stores/page.js
  frontend/app/purchase-history/page.js
  frontend/components/Sidebar.jsx
Labels: enhancement

#353 352 removing location id from adding a store
  backend/business/DTOs.py
  backend/business/market.py
  backend/business/store/new_store.py
  backend/services/store_services/controllers.py
  backend/services/store_services/routes.py
  tests/acceptance_test_checkout.py
  tests/acceptance_tests_roles.py
  tests/acceptance_tests_system_manager.py
  tests/acceptance_tests_user.py
  tests/concurrency_test.py
  tests/integration_tests.py
  tests/notification_test.py
  tests/store_owner_actions_acceptance_test.py
  tests/store_owner_more_actions_acceptance_test.py
  tests/unit_tests/test_new_store.py
Labels: bug

#359 no results found message works
  backend/business/store/new_store.py
  frontend/app/search_products/search_by_category/page.js
  frontend/app/search_products/search_by_name/page.js
  frontend/app/search_products/search_by_tags/page.js
Labels: bug, enhancement

#364 open and close store work!
  backend/business/market.py
  backend/business/store/new_store.py
  backend/services/store_services/controllers.py
  backend/services/store_services/routes.py
  frontend/app/e-store/[storeid]/[productid]/page.js
  frontend/app/stores/[storeId]/page.js
Labels: enhancement

#368 365 add tags to store
  backend/business/store/new_store.py
Labels: enhancement
