Repository Sadna-Team/TradeCenter, pull requests merged in 2024-05, with the labels that each got.

#85 79 fix integration bugs
  backend/business/market.py
  backend/business/purchase/purchase.py
  backend/business/store/store.py
  backend/logging_config.py
Labels: bug, documentation

#86 82 more acceptance tests
  .gitignore
  backend/__init__.py
  backend/services/third_party_services/controllers.py
  backend/services/third_party_services/routes.py
Labels: documentation, enhancement

#90 77 trying to unify tests under a single directory
  backend/business/market.py
  backend/business/notifier/notifier.py
  backend/business/store/__init__.py
  backend/services/ecommerce_services/routes.py
  backend/services/store_services/routes.py
  backend/services/user_services/routes.py
  backend/tests/test_purchase.py
  tests/acceptance_test.py
  tests/unit_tests/__init__.py
  tests/unit_tests/test_authentication.py
  tests/unit_tests/test_notifier.py
  tests/unit_tests/test_purchase.py
  tests/unit_tests/test_roles.py
  tests/unit_tests/test_store.py
  tests/unit_tests/test_third_party_handlers.py
  tests/unit_tests/test_user.py
  tests/unit_tests/test_user_services.py
Labels: documentation, enhancement

#92 all working!!
  backend/business/purchase/__pycache__/__init__.cpython-312.pyc
  backend/business/purchase/__pycache__/purchase.cpython-312.pyc
  backend/business/purchase/purchase.py
  backend/services/ecommerce_services/routes.py
  backend/services/store_services/routes.py
  backend/services/third_party_services/__pycache__/__init__.cpython-312.pyc
  backend/services/third_party_services/__pycache__/controllers.cpython-312.pyc
  backend/services/third_party_services/__pycache__/routes.cpython-312.pyc
  backend/services/user_services/routes.py
Labels: documentation, enhancement

#97 ready to write tests for tps
  backend/business/ThirdPartyHandlers/third_party_handlers.py
  backend/business/market.py
  backend/services/third_party_services/controllers.py
  backend/services/third_party_services/routes.py
Labels: documentation, enhancement

#103 removed cached, updated .gitignore
  backend/business/purchase/__pycache__/__init__.cpython-311.pyc
  backend/business/purchase/__pycache__/__init__.cpython-312.pyc
  backend/business/purchase/__pycache__/purchase.cpython-311.pyc
  backend/business/purchase/__pycache__/purchase.cpython-312.pyc
  backend/services/third_party_services/__pycache__/__init__.cpython-312.pyc
  backend/services/third_party_services/__pycache__/controllers.cpython-312.pyc
  backend/services/third_party_services/__pycache__/routes.cpython-312.pyc
Labels: bug

#106 Store purchase service+checkout
  backend/business/market.py
  backend/business/store/store.py
  backend/services/ecommerce_services/routes.py
  backend/services/store_services/routes.py
Labels: bug, enhancement

#112 87 acceptance tests for store purchase uc
  backend/business/ThirdPartyHandlers/third_party_handlers.py
  backend/business/market.py
  backend/business/roles/roles.py
  backend/services/third_party_services/controllers.py
  backend/services/third_party_services/routes.py
  backend/tests/test_authentication.py
  tests/acceptance_test.py
  tests/unit_tests/test_roles.py
  tests/unit_tests/test_user_services.py
Labels: bug, documentation, enhancement

#118 111 merging productspec with product
  backend/business/store/store.py
Labels: bug, documentation, enhancement
